name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Adjust the PHP version as needed

    - name: Install dependencies
      run: composer install

    - name: Execute PHP script
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Setting the secret as an environment variable
      run: php api/connection/config.php
